USE CUSTOMER

CREATE TABLE EMPLOYEE(
ID INT PRIMARY kEY,
NAME VARCHAR(50),
MANAGER_ID INT);

INSERT INTO EMPLOYEE(ID,NAME,MANAGER_ID)
VALUES
(101,'ADAM',103),
(102,'AMIT',104),
(103,'RAJ',NULL),
(104,'JAY',103);

SELECT * FROM EMPLOYEE;

SELECT NAME FROM EMPLOYEE
UNION
SELECT NAME FROM EMPLOYEE;