USE NPPS;
CREATE TABLE FORKINFOSYSTEM(
rollno INT PRIMARY KEY ,
name VARCHAR(50),
marks INT NOT NULL,
grade VARCHAR(1),
city VARCHAR(20),
);


INSERT INTO FORKINFOSYSTEM
(rollno,name,marks,grade,city)
VALUES
(101,'Sarikha Patil',80,'B','Pune'),
(102,'Sahil Mane',90,'A','Pune'),
(103,'Atharv More',95,'A','Satara'),
(104,'Kunal Mohite',70,'C','Pune'),
(105,'Arya More',85,'A','Satara');

INSERT INTO FORKINFOSYSTEM VALUES (106,'Rahul More',90,'A','Satara');
SELECT * FROM FORKINFOSYSTEM;

SELECT CITY FROM FORKINFOSYSTEM
GROUP BY CITY;

SELECT CITY,COUNT(rollno)
FROM FORKINFOSYSTEM
GROUP BY CITY;

SELECT CITY,name,COUNT(rollno)
FROM FORKINFOSYSTEM
GROUP BY CITY,name;

SELECT CITY,AVG(MARKS)
FROM FORKINFOSYSTEM
GROUP BY CITY;