USE NPPS;
SELECT * FROM STUDENT;
INSERT INTO STUDENT (rollno,name,marks,grade,city)
VALUES
(108,'Karan salunkhe',90,'A','Satara');
SELECT * FROM STUDENT;
SELECT DISTINCT city FROM STUDENT;
SELECT * FROM STUDENT ORDER BY marks ASC;
