CREATE database STUDENT_DETAILS;
USE STUDENT_DETAILS;

CREATE TABLE STD_DETAILS(
ROLL_NO INT PRIMARY KEY,
NAME varchar(40),
PERSENTAGE INT,
CITY varchar(20) 
);
select * FROM STD_DETAILS;
INSERT INTO STD_DETAILS
(ROLL_NO,NAME,PERSENTAGE,CITY)
VALUES
(101,'SAHIL MANE',80,'KARAD'),
(102,'SAGAR PATIL',90,'KARAD'),
(103,'SUNITA RAUT',89,'KARAD'),
(104,'SAYALI MORE',70,'KARAD'),
(105,'SANIKA PATIL',75,'KARAD');

SELECT * FROM STD_DETAILS
ORDER BY PERSENTAGE;

SELECT * FROM STD_DETAILS
ORDER BY PERSENTAGE desc
limit 1;

SELECT * FROM STD_DETAILS
WHERE PERSENTAGE >=80;

INSERT INTO STD_DETAILS
(ROLL_NO,NAME,PERSENTAGE,CITY)
VALUES
(106,'RAJ JADHAV',91,'SATARA'),
(107,'ANJALI JADHAV',90,'PUNE'),
(108,'SOHEL GUPTA',89,'SATARA'),
(109,'ABHAY JADHAV',98,'PUNE');

SELECT CITY,PERSENTAGE,  COUNT(CITY)
FROM STD_DETAILS
GROUP BY CITY
HAVING MIN(PERSENTAGE)>85
order by PERSENTAGE DESC; 