use NPPS;

CREATE TABLE STUDENT_RESULT
(
ROLLNO INT PRIMARY KEY,
NAME VARCHAR(50),
MARKS INT NOT NULL,
AGE INT NOT NULL,
CITY VARCHAR(20),
);

INSERT INTO STUDENT_RESULT (ROLLNO,NAME,MARKS,AGE,CITY)
VALUES
(101,'Rahul More',80,18,'Karad');
select * from STUDENT_RESULT;

INSERT INTO STUDENT_RESULT (ROLLNO,NAME,MARKS,AGE,CITY)
VALUES
(102,'Rohit More',85,18,'Karad');
select * from STUDENT_RESULT;
INSERT INTO STUDENT_RESULT (ROLLNO,NAME,MARKS,AGE,CITY)
VALUES
(103,'Rohit More',85,18,'Karad'),
(104,'Raj Mane',90,19,'Satara');
INSERT INTO STUDENT_RESULT (ROLLNO,NAME,MARKS,AGE,CITY)
VALUES
(105,'Tanmay Sutar',90,18,'Karad'),
(106,'Suyash Jaktap',85,18,'Satara'),
(107,'Aryan Khot',70,18,'Pune'),
(108,'Omakar Mohite',87,19,'Pune');
select * from STUDENT_RESULT;

select AVG(MARKS)
FROM STUDENT
ORDER BY AVG(MARKS);

SELECT CITY,AVG(MARKS)
FROM STUDENT_RESULT
GROUP BY CITY
ORDER BY AVG(MARKS)DESC;