use COLLEGE;





SELECT * FROM EMPLOYEE;

UPDATE EMPLOYEE SET SALARY = 70000 WHERE id = 4;

select * from EMPLOYEE ORDER BY CITY ;
 DELETE FROM EMPLOYEE;
 TRUNCATE TABLE EMPLOYEE;

 DROP TABLE EMPLOYEE;
  
SELECT MAX (SALARY),CITY FROM EMPLOYEE GROUP BY CITY ORDER BY MAX(SALARY) ;
SELECT MAX (SALARY),NAME FROM EMPLOYEE WHERE SALARY <(SELECT MAX (SALARY) FROM EMPLOYEE);
SELECT CITY COUNT FROM EMPLOYEE;
SELECT id, NAME FROM EMPLOYEE;
SELECT MIN (SALARY),CITY FROM EMPLOYEE GROUP BY CITY;

SELECT AVG(SALARY),CITY FROM EMPLOYEE GROUP BY CITY;
SELECT SUM(SALARY),CITY FROM EMPLOYEE GROUP BY CITY ORDER BY SUM(SALARY)DESC;

SELECT id, NAME,AGE,CITY  FROM EMPLOYEE WHERE AGE >=23;

CREATE TABLE DEPARTMENT(
dID INT PRIMARY KEY,
DEPT_NM VARCHAR(40),
);

CREATE TABLE EMPLOYEE(
id INT PRIMARY KEY,
NAME VARCHAR(50),
AGE INT NOT NULL,
CITY VARCHAR(20),
SALARY MONEY,
DID INT, FOREIGN KEY(DID) REFERENCES DEPARTMENT(DID)
);

SELECT * FROM DEPARTMENT;


INSERT INTO DEPARTMENT(DID,DEPT_NM) VALUES
(101,'CS'),
(102,'DS'),
(103,'CA');

INSERT INTO EMPLOYEE(id,NAME,AGE,CITY,SALARY,DID) 
VALUES
(1,'SAKSHI',22,'PUNE',20000,101),
(2,'SANSKRUTI',22,'SATARA',25000,102),
(3,'TEJSWINI',23,'PATAN',30000,102),
(4,'VAISHNAVI',21,'KARAD',15000,103),
(5,'MAYA',22,'KARAD',80000,101),
(6,'SUCHITA',23,'SATARA',30000,102);

TRUNCATE TABLE EMPLOYEE;

SELECT * FROM EMPLOYEE;

SELECT * 
FROM EMPLOYEE
INNER JOIN DEPARTMENT
ON EMPLOYEE.DID = DEPARTMENT.DID;